language: php
php:
  - 5.4
  - 5.5
  - 5.6
  
# Command to install dependencies
install:
    - python setup.py sdist
    - sudo pip install dist/jasmin-0.6rc40.tar.gz
    - sudo cp misc/config/init-script/jasmind-ubuntu /etc/init.d/jasmind
    - sudo update-rc.d jasmind defaults
# Commands to run tests:
script:
    # phpunit test
    - phpunit JcliTest.php
services:
    - rabbitmq
    - redis-server
    - jasmind
before_script:
    # - sudo invoke-rc.d jasmind start
before_install:
    - sudo apt-get update -qq
    # jasmin installation requirement:
    # As documented here http://docs.jasminsms.com/en/latest/installation/index.html
    - sudo apt-get install -qq python-dev libffi-dev libssl-dev
    - sudo useradd jasmin
    - sudo mkdir -p /var/log/jasmin /etc/jasmin/resource /etc/jasmin/init-script /etc/jasmin/store /var/run/jasmin
    - sudo chown `whoami` /etc/jasmin /etc/jasmin/resource /etc/jasmin/init-script
    - sudo chown jasmin. /var/log/jasmin /etc/jasmin/store /var/run/jasmin
notifications:
    slack:
        secure: guCY7vL67vUhvNYLzInV/EIPMZ7ciq+/s0UlfmKvGYrjIMwXdgfshgKXdHF194eQ9+f0dF8ea1P1/aGqCE4Q4ULPZ555FbftNy/bVLfUPn01+odorAux3rVNq4ezX2QlQc06DpVS2r7U+grM+MQtNdRjoZIuAeipp3YRhyyuIr8=
